name: Go

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main  # Trigger CI on main branch
  pull_request:
    branches:
      - main  # Trigger gated pipeline on PR to main

jobs:
  build:
    strategy:
      matrix:
        go-version: ['1.21']
        platform: [ "windows/amd64", "linux/arm", "linux/arm64", "linux/amd64", "linux/386" ]   # target multiple platforms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
